// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dhloljsfwwwtuvvmzxoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRobG9sanNmd3d3dHV2dm16eG9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4MTExMzMsImV4cCI6MjA2ODM4NzEzM30.2CBiwg4SNUUOmkcC83_FIn_pUkWdoO2pTKEZhKIUH_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});